:Author: ard12sgf1960
:Email: {AuthorEmail}
:Date: 11/11/2022
:Revision: version#
:License: Public Domain

= Project: {Pot_and_LEDS}

Turn on a bank of LEDs based on the position of a potentiometer

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Pot_and_LEDS             => Arduino sketch folder
  ├── Pot_and_LEDS.ino    => main Arduino file
  ├── Pot_and_LED.jpg     => an image of the connected breadboard
  ├── RP2040_Pinout.png   => an image of the RP2040 pinouts
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact ard12sgf1960 https://id.arduino.cc/ard12sgf1960

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name        | Part number | Quantity
| R1 | 330 Resistor     | COM-B005    | 5
| L1 | Red LED          |             | 1
| L2 | Green LED        |             | 1
| L3 | Blue LED         |             | 1
| L4 | Yellow LED       |             | 1
| L5 | White LED        |             | 1
| P1 | 1k Potentiometer | COM1003     | 1
| A1 | Nano RP2040      | BX00052     | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
