:Author: ard12sgf1960
:Email: {AuthorEmail}
:Date: 11/11/2022
:Revision: version#
:License: Public Domain

= Project: {Pot_and_LEDS}

Turn on a bank of LEDs based on the position of a potentiometer
The Nano RP2040 Connect partly uses the NINA WiFi/Bluetooth module to control some pins
Because of this, the code only uses 3 outputs as using more corrupts the outputs and therefore the effect


== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

== Step 4: Function

|===
| Mode |      Type       | LEDS
|  0   | Sequential      | R-G-B-R-G-B-R
|  1   | Cascade         | R-RG-RGB-RG-R-RG-RGB-RG-R
|  2   | Fade Sequential | R-G-B-R-G-B-R
|  3   | Fade Cascade    | R-RG-RGB-RG-R-RG-RGB-RG-R
|===

=== Folder structure

....
 Pot_and_LEDS             => Arduino sketch folder
  ├── Pot_and_LEDS.ino    => main Arduino file
  ├── Pot_and_LED.jpg     => an image of the connected breadboard
  ├── RP2040_Pinout.png   => an image of the RP2040 pinouts
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact ard12sgf1960 https://id.arduino.cc/ard12sgf1960

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name        | Part number | Quantity
| R1 | 330 Resistor     | COM-B005    | 6
| L1 | Red LED          |             | 2
| L2 | Green LED        |             | 2
| L3 | Blue LED         |             | 2
| P1 | 1k Potentiometer | COM1003     | 1
| A1 | Nano RP2040      | BX00052     | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
